
slides:
  - title: Мероприятия
    slug: organization
    image: ./assets/images/organization.jpg
    body:   <b>Организация и проведение мероприятий любой направленности:</b><br> 1) Спортивные<br> 2) Культурные<br> 3) Церемонии открытий и корпоративные мероприятия<br> 4) Благотворительные 5) Пресс-конференции<br> 6) Пиар компаний, рекламные акций<br> 7) Флэш-мобы<br> 8) Выстави<br> 9) Музыкальные концерты<br> 10) Организация питания (кейтеринг)<br> 11) Организация продаж сувинирной продукции<br> 12)Организация питания (кейтеринг) и продаж сувенирной продукции на мероприятиях.
    id: 1
  - title: Медиа
    slug: media
    image: ./assets/images/media.jpg
    body: Медиа студия полного производства, фото и видео съёмка.
    id: 2
  - title: IT-технологии
    slug: it-tech
    image: ./assets/images/it-tech.jpg
    body: Разработка сайтов, приложений, организация технической и программной работы серверов и оборудования
    id: 3
  - title: Производство
    slug: prodaction
    image: ./assets/images/prodaction.jpg
    body: Производство одежды, сувенирной продукции, наградной атрибутики.<br> 1) Кубки, жетоны, значки, медали, дипломы и тд<br> 2) Спортивная одежда, костюмы, кепки, шарфы
    id: 4
  - title: Типография
    slug: typography
    image: ./assets/images/typography.jpg
    body: "- Издательская деятельность<br> - Печать<br> - Распространение"
    id: 5
  - title: Реклама
    slug: advertising
    image: ./assets/images/a_d_vertising.jpg
    body:   Рекламная деятельность.<br> 1) Создание рекламных металлических конструкций<br> 2) Резьба по металлу<br> 3) Световые декорации любой сложности<br> 4) Арт реклама<br> 5) разработка и проведение рекламной компании продукта или организации
    id: 6
  - title: Продюссирование
    slug: producing
    image: ./assets/images/organization.jpg
    body: Продюссерская деятельность в сфере культуры, кино и шоу бизнеса.
    id: 7
  - title: Инф. поддержка
    slug: inf-help
    image: ./assets/images/inf-help.jpg
    body: Организация информационной поддержки проекта, услуги, продукта.
    id: 8
  - title: Волонтерство
    slug: volunteering
    image: ./assets/images/volunteering.jpg
    body: Предоставление волонтёров на мероприятия.
    id: 9
  - title: СМИ
    slug: promotion
    image: ./assets/images/promotion.jpg
    body: Продвижение в СМИ и социальных сетях
    id: 10
  - title: Аналитика
    slug: analytic
    image: ./assets/images/analytic.jpg
    body:  Консалтинг и аналитика потребительского рынка<br> 1) Индустрия спорта ( мерчендайзинг, СМИ, сфера услуг, производство, строительный бизнес)<br> 2) Индустрия развлечений (киноиндустрия, музыка, искусство, театр)<br> 3) Сфера IT (добавить какую аналитику можно сделать и какие консультации дать)<br> 4) Анализ потребительского рынка молодёжи и детей
    id: 11
  - title: Дизайн
    slug: design
    image: ./assets/images/design.jpg
    body: Дизайнерская деятельность, промышленный дизайн<br> 1) Дизайн продукта, товара<br> 2) Дизайн бренда, логотипа<br> 3) Дизайн упаковки, тары<br> 4) Дизайн линейки бренда, продукта<br><br> Стрит-Арт оформление объектов, монументальная живопись.<br> 1) Фасады дома<br> 2) Офисы<br> 3) Спортивные площадки<br> 4) Интерьеры
    id: 12
