
slides:
  - title: Мероприятия
    slug: organization
    image: ./assets/images/organization.jpg
    body:   <b>Организация и проведение мероприятий любой направленности:</b><br> - Спортивные<br> - Культурные<br> - Церемонии открытий и корпоративные мероприятия<br> - Благотворительные <br>- Пресс-конференции<br> - Пиар компаний, рекламные акций<br> - Флэш-мобы<br> - Выстави<br> - Музыкальные концерты<br> - Организация продаж сувинирной продукции
    id: 1
  - title: Медиа
    slug: media
    image: ./assets/images/media.jpg
    body: Медиа студия полного производства, фото и видео съёмка.
    id: 2
  - title: IT-технологии
    slug: it-tech
    image: ./assets/images/it-tech.jpg
    body: Разработка сайтов, приложений, организация технической и программной работы серверов и оборудования
    id: 3
  - title: Производство
    slug: prodaction
    image: ./assets/images/prodaction.jpg
    body: Производство одежды, сувенирной продукции, наградной атрибутики.<br> - Кубки, жетоны, значки, медали, дипломы и тд<br> - Спортивная одежда, костюмы, кепки, шарфы
    id: 4
  - title: Типография
    slug: typography
    image: ./assets/images/typography.jpg
    body: "- Издательская деятельность<br> - Печать<br> - Распространение"
    id: 5
  - title: Реклама
    slug: advertising
    image: ./assets/images/a_d_vertising.jpg
    body:   Рекламная деятельность.<br> - Создание рекламных металлических конструкций<br> - Резьба по металлу<br> - Световые декорации любой сложности<br> - Арт реклама<br> - разработка и проведение рекламной компании продукта или организации
    id: 6
  - title: Продюссирование
    slug: producing
    image: ./assets/images/organization.jpg
    body: Продюссерская деятельность в сфере культуры, кино и шоу бизнеса.
    id: 7
  - title: Инф. поддержка
    slug: inf-help
    image: ./assets/images/inf-help.jpg
    body: Организация информационной поддержки проекта, услуги, продукта.
    id: 8
  - title: Добровольчество
    slug: volunteering
    image: ./assets/images/volunteering.jpg
    body: Предоставление волонтёров на мероприятия.
    id: 9
  - title: Туризм
    slug: tourism
    image: ./assets/images/tourism.jpg
    body: >
        - Разработка индивидуальных маршрутов и программ tailor-made (включая оздоровительный отдых на СПА-курортах, центрах талассотерапии, организацию свадебных церемоний, винно-гастрономические туры); авторские программы путешествий;
        <br> -Подбор готовых программ (экскурсионные маршруты, отдых на море) по оптимальным ценам с гарантированным качеством;
        <br> -Бронирование авиабилетов, проработка и оптимизация сложных маршрутов;
        <br> -Организация экскурсионных программ с предоставлением услуг профессиональных лицензированных гидов;
        <br> -Содействие в оформлении виз, в том числе подготовка документов для передачи в консульские отделы при посольствах государств Великобритания, США, Канада;
        <br> -Транспортные услуги (организация трансферов и аренда автомобилей за рубежом);
        <br> -Аренда яхт, автомобилей класса Люкс, вилл и частных островов;
        <br> -Бронирование услуг VIP-залов в аэропортах России и за рубежом.
    id: 10
  - title: Кейтеринг
    slug: catering
    image: ./assets/images/catering.jpg
    body: >
       <br>Наши возможности:
       <br>- Доставка обедов для персонала
       <br>- Организация кофе-брейков для тренингов и совещаний
       <br>- Сопровождение презентаций и выставок.
       <br>- Подготовка и воплощение в жизнь разовых банкетов, фуршетов, пикников
       <br>Наши преимущества:
        <br>- Гибкое меню, широкий выбор блюд от лучшего шеф-повара.
        <br>- Слаженная и четкая работа обслуживающего персонала.
        <br>- Контроль качества на каждом этапе взаимодействия с заказчиком.
        <br>- Представление персонального менеджера, несущего ответственность за организацию выездного обслуживания.
        <br>- Качественное и оперативное оказание всех, прописанных в договоре, услуг.
        <br>- Разработка креативных вариантов оформления помещений с учетом ваших пожеланий и тематикой праздника.
        <br>- Эксклюзивность концепции проведения.<br>
    id: 11
  - title: Дизайн
    slug: design
    image: ./assets/images/design.jpg
    body: Дизайнерская деятельность, промышленный дизайн<br> - Дизайн продукта, товара<br> - Дизайн бренда, логотипа<br> - Дизайн упаковки, тары<br> - Дизайн линейки бренда, продукта<br><br> Стрит-Арт оформление объектов, монументальная живопись.<br> - Фасады дома<br> - Офисы<br> - Спортивные площадки<br> - Интерьеры
    id: 12
