
slides:
  - title: Организация
    image: ./assets/images/organization.jpg
    body:   <b>Организация и проведение мероприятий любой направленности:</b><br> 1) Спортивные<br> 2) Культурные<br> 3) Церемонии открытий и корпоративные мероприятия<br> 4) Благотворительные 5) Пресс-конференции<br> 6) Пиар компаний, рекламные акций<br> 7) Флэш-мобы<br> 8) Выстави<br> 9) Музыкальные концерты<br> 10) Организация питания (кейтеринг)<br> 11) Организация продаж сувинирной продукции<br> 12)Организация питания (кейтеринг) и продаж сувенирной продукции на мероприятиях.
    id: 1
  - title: Медиа
    image: ./assets/images/media.jpg
    body: Медиа студия полного производства, фото и видео съёмка любого уровня. <br> (Цена договорная, зависит от количества оборудования, необходимого уровня съёмки и времени)
    id: 2
  - title: IT-технологии
    image: ./assets/images/it-tech.jpg
    body: Разработка сайтов, приложений, организация технической и программной работы серверов и оборудования
    id: 3
  - title: Производство
    image: ./assets/images/prodaction.jpg
    body: Производство одежды, сувенирной продукции, наградной атрибутики. (Цена зависит от количества единиц и сложности производства)<br> 1) Кубки, жетоны, значки, медали, дипломы и тд<br> 2) Спортивная одежда, костюмы<br> 3) Сувенирная одежда, кепки, банданы
    id: 4
  - title: Типография
    image: ./assets/images/typography.jpg
    body: Типография, издательская деятельность.<br> 1) Оформление дизайна<br> 2) Печать<br> 3) Распространение
    id: 5
  - title: Реклама
    image: ./assets/images/organization.jpg
    body:   Рекламная деятельность.<br> 1) Создание рекламных металлических конструкций<br> 2) Резьба по металлу<br> 3) Световые декорации любой сложности<br> 4) Арт реклама<br> 5) разработка и проведение рекламной компании продукта или организации
    id: 6
  - title: Продюсерство
    image: ./assets/images/advertising.jpg
    body: Продюсерская деятельность в сфере культуры, кино и шоу бизнеса:<br> 1) Киноиндустрия<br> 2) Музыка<br> 3) Искусство
    id: 7
  - title: Инф. поддержка
    image: ./assets/images/inf-help.jpg
    body: Информационная поддержка проекта<br> 1) информационные порталы<br> 2) ютуб-каналы<br> 3) соц.сети
    id: 8
  - title: Волонтерство
    image: ./assets/images/volunteering.jpg
    body: Предоставление волонтёров на мероприятия любого уровня:<br> 1) коммерческие мероприятия<br> 2) некоммерческие мероприятия
    id: 9
  - title: СМИ
    image: ./assets/images/promotion.jpg
    body: Продвижение в СМИ и социальных сетях (цена зависит от объекта продвижения, способов и длительности периода работы)
    id: 10
  - title: Аналитика
    image: ./assets/images/analytic.jpg
    body:  Консалтинг и аналитика потребительского рынка<br> 1) Индустрия спорта ( мерчендайзинг, СМИ, сфера услуг, производство, строительный бизнес)<br> 2) Индустрия развлечений (киноиндустрия, музыка, искусство, театр)<br> 3) Сфера IT (добавить какую аналитику можно сделать и какие консультации дать)<br> 4) Анализ потребительского рынка молодёжи и детей
    id: 11
  - title: Дизайн
    image: ./assets/images/design.jpg
    body: Дизайнерская деятельность, промышленный дизайн<br> 1) Дизайн продукта, товара<br> 2) Дизайн бренда, логотипа<br> 3) Дизайн упаковки, тары<br> 4) Дизайн линейки бренда, продукта<br><br> Граффити оформление объектов, монументальная живопись. Стоимость услуги зависит от размеров объекта, сложности и стиля исполнения (от 15 тыс. руб.)<br> 1) Фасад дома<br> 2) Офис<br> 3) Спортивные площадки<br> 4) Интерьер
    id: 12
